### ISSUE TITLE
crear tabla comentarios

### ISSUE THREAD

**Issue by frako23** [frako23/LinkedTeam#18]
igual, que tenga el id de comentario, que se relacione con el usuario que hace el comentario y el texto con el comentario como tal

Debe tener los métodos:

- GET
- POST
- DELETE

**Comment by danielmoret** [comment]
bb5f67d193d9ce889641202e37eb401d0385edb7

**Comment by danielmoret** [comment]
endpoint de la tabla comentarios a9b165673ae53f01e27dd67bd7e6ac88416de3a4 17d017ef599cf25f31621e508550a445d64b4f2c
